INSERT INTO PERSONNESMORALES(RAISONSOCIALE, RUENUMERO, CODEPOSTAL, LOCALITE) VALUES ('ABC SA', 'Plaine 2', '20000', 'Neuchatel');	
INSERT INTO QUALIFICATIONS(LIBELLE, TARIFHORAIRE) VALUES ('Bach. HES',160);
UPDATE QUALIFICATIONS SET TARIFHORAIRE=0 WHERE LIBELLE='CFC';
UPDATE COLLABORATEURS SET QUAL_CONCERNER_NUMERO=9999 WHERE MNEMO='FL';
UPDATE COLLABORATEURS SET QUAL_CONCERNER_NUMERO = NULL WHERE MNEMO='FL';
UPDATE MANDATS SET NBHEURESCHEFPROJET=-10;
INSERT INTO REALISATIONS (MAND_NUMERO, COL_NUMERO, NBHEURES)
VALUES ( (SELECT NUMERO FROM MANDATS WHERE
		 (PM_CLIENT_NUMERO = (SELECT NUMERO FROM PERSONNESMORALES WHERE RAISONSOCIALE ='Cablo SA')) AND
		 (DATESIGNATURE = TO_DATE('25.08.2015','DD.MM.YYYY'))),
		 (SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO = 'CP'),
		 148 );
UPDATE MANDATS SET PM_CLIENT_NUMERO=(SELECT NUMERO FROM PERSONNESMORALES WHERE RAISONSOCIALE='Cablo SA') WHERE REFERENCE='FA-2015.02';		 
		 
