-- Vider les tables
DELETE FROM REALISATIONS;
DELETE FROM MANDATS;
DELETE FROM COLLABORATEURS;
DELETE FROM PERSONNESMORALES;
DELETE FROM QUALIFICATIONS;

-- Script de peuplement de la table PERSONNESMORALES
INSERT INTO PERSONNESMORALES(RAISONSOCIALE, RUENUMERO, CODEPOSTAL, LOCALITE)
VALUES ('Les Frimousses', 'Gare 28', '2088', 'Cressier');

INSERT INTO PERSONNESMORALES(RAISONSOCIALE, RUENUMERO, CODEPOSTAL, LOCALITE)
VALUES ('Crayons et Jeux SA', 'Forêt 3a', '2087', 'Cornaux');
 
INSERT INTO PERSONNESMORALES(RAISONSOCIALE, RUENUMERO, CODEPOSTAL, LOCALITE)
VALUES ('Du Bais Peintures', 'Enhaut', '2105', 'Travers');

INSERT INTO PERSONNESMORALES(RAISONSOCIALE, RUENUMERO, CODEPOSTAL, LOCALITE)
VALUES ('A la mèche d''or', 'Mont 13', '2108', 'Couvet');

INSERT INTO PERSONNESMORALES(RAISONSOCIALE, RUENUMERO, CODEPOSTAL, LOCALITE)
VALUES ('ABC SA', 'Plaine 2', '2000', 'Neuchatel');

INSERT INTO PERSONNESMORALES(RAISONSOCIALE, RUENUMERO, CODEPOSTAL, LOCALITE)
VALUES ('Cablo SA', 'Peupliers 33a', '1000', 'Lausanne');

INSERT INTO PERSONNESMORALES(RAISONSOCIALE, RUENUMERO, CODEPOSTAL, LOCALITE)
VALUES ('Jeux et modèles', 'Revert 3', '2087', 'Cornaux');

-- Script de peuplement de la table des qualifications
INSERT INTO QUALIFICATIONS(LIBELLE, TARIFHORAIRE) VALUES ('CFC',60);
INSERT INTO QUALIFICATIONS(LIBELLE, TARIFHORAIRE) VALUES ('ES',120);
INSERT INTO QUALIFICATIONS(LIBELLE, TARIFHORAIRE) VALUES ('Bach. HES',140);
INSERT INTO QUALIFICATIONS(LIBELLE, TARIFHORAIRE) VALUES ('Bach. UNI',130);
INSERT INTO QUALIFICATIONS(LIBELLE, TARIFHORAIRE) VALUES ('Master HES',160);
INSERT INTO QUALIFICATIONS(LIBELLE, TARIFHORAIRE) VALUES ('Master UNI',150);


-- Script de peuplement de la table des collaborateurs
INSERT INTO COLLABORATEURS(MNEMO, NOM, PRENOM, QUAL_CONCERNER_NUMERO)
VALUES ('YC', 'Callard', 'Yves',
	(SELECT NUMERO FROM QUALIFICATIONS WHERE (LIBELLE='ES'))  );

INSERT INTO COLLABORATEURS(MNEMO, NOM, PRENOM, QUAL_CONCERNER_NUMERO)
VALUES ('FL', 'Lebeu', 'Fred',
	(SELECT NUMERO FROM QUALIFICATIONS WHERE (LIBELLE='CFC'))  );

INSERT INTO COLLABORATEURS(MNEMO, NOM, PRENOM, QUAL_CONCERNER_NUMERO)
VALUES ('VJ', 'Jeune', 'Vincent',
	(SELECT NUMERO FROM QUALIFICATIONS WHERE (LIBELLE='CFC'))  );

INSERT INTO COLLABORATEURS(MNEMO, NOM, PRENOM, QUAL_CONCERNER_NUMERO)
VALUES ('CP', 'Paris', 'Claude',
	(SELECT NUMERO FROM QUALIFICATIONS WHERE (LIBELLE='Bach. UNI'))  );

INSERT INTO COLLABORATEURS(MNEMO, NOM, PRENOM, QUAL_CONCERNER_NUMERO)
VALUES ('SA', 'Auclair', 'Stephan',
	(SELECT NUMERO FROM QUALIFICATIONS WHERE (LIBELLE='Bach. HES'))  );

INSERT INTO COLLABORATEURS(MNEMO, NOM, PRENOM, QUAL_CONCERNER_NUMERO)
VALUES ('MD', 'Daran', 'Marie',
	(SELECT NUMERO FROM QUALIFICATIONS WHERE (LIBELLE='Bach. UNI'))  );

INSERT INTO COLLABORATEURS(MNEMO, NOM, PRENOM, QUAL_CONCERNER_NUMERO)
VALUES ('AM', 'Moine', 'Annie',
	(SELECT NUMERO FROM QUALIFICATIONS WHERE (LIBELLE='ES'))  );

INSERT INTO COLLABORATEURS(MNEMO, NOM, PRENOM, QUAL_CONCERNER_NUMERO)
VALUES ('CF', 'Fallet', 'Cindy',
	(SELECT NUMERO FROM QUALIFICATIONS WHERE (LIBELLE='CFC'))  );

INSERT INTO COLLABORATEURS(MNEMO, NOM, PRENOM, QUAL_CONCERNER_NUMERO)
VALUES ('AK', 'Kaffe', 'Ariane',
	(SELECT NUMERO FROM QUALIFICATIONS WHERE (LIBELLE='CFC'))  );

INSERT INTO COLLABORATEURS(MNEMO, NOM, PRENOM, QUAL_CONCERNER_NUMERO)
VALUES ('CC', 'Cattin', 'Claude',
	(SELECT NUMERO FROM QUALIFICATIONS WHERE (LIBELLE='ES'))  );

INSERT INTO COLLABORATEURS(MNEMO, NOM, PRENOM, QUAL_CONCERNER_NUMERO)
VALUES ('CS', 'Sarre', 'Claude',
	(SELECT NUMERO FROM QUALIFICATIONS WHERE (LIBELLE='Bach. HES'))  );

INSERT INTO COLLABORATEURS(MNEMO, NOM, PRENOM, QUAL_CONCERNER_NUMERO)
VALUES ('CD', 'Daran', 'Claude',
	(SELECT NUMERO FROM QUALIFICATIONS WHERE (LIBELLE='ES'))  );


-- Script de peuplement de la table des mandats
	
INSERT INTO MANDATS(	PM_CLIENT_NUMERO, DATESIGNATURE, REFERENCE, DESCRIPTION, 
						DATEDEBUT, DATEFINPREVUE,
						COL_CHEFPROJET_NUMERO, NBHEURESCHEFPROJET,
						COL_MANDCOM_NUMERO, NBHEURESMANDCOM		)
VALUES ( 	(SELECT NUMERO FROM PERSONNESMORALES WHERE RAISONSOCIALE ='ABC SA'), 
			TO_DATE('15.07.2015','DD.MM.YYYY'),
			'FA-2015.01','Logiciel de facturation',
			TO_DATE('10.08.2015','DD.MM.YYYY'),
			TO_DATE('15.10.2015','DD.MM.YYYY'),
			(SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO ='CP'), 80,
			(SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO ='AM'), 5	);

-- 2ème mandat
INSERT INTO MANDATS(	PM_CLIENT_NUMERO, DATESIGNATURE, REFERENCE, DESCRIPTION,
						DATEDEBUT, DATEFINPREVUE,
						COL_CHEFPROJET_NUMERO, NBHEURESCHEFPROJET,
						COL_MANDCOM_NUMERO, NBHEURESMANDCOM		)
VALUES ( 	(SELECT NUMERO FROM PERSONNESMORALES WHERE RAISONSOCIALE ='Crayons et Jeux SA'), 
			TO_DATE('02.05.2015','DD.MM.YYYY'),
			'FA-2015.02','Logiciel de facturation',
			TO_DATE('10.05.2015','DD.MM.YYYY'),
			TO_DATE('30.07.2015','DD.MM.YYYY'),
			(SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO ='MD'), 60,
			(SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO ='AM'), 5	);

-- 3ème mandat
INSERT INTO MANDATS(	PM_CLIENT_NUMERO, DATESIGNATURE, REFERENCE, DESCRIPTION,
						DATEDEBUT, DATEFINPREVUE,
						COL_CHEFPROJET_NUMERO, NBHEURESCHEFPROJET,
						COL_MANDCOM_NUMERO, NBHEURESMANDCOM		)
VALUES ( 	(SELECT NUMERO FROM PERSONNESMORALES WHERE RAISONSOCIALE ='Crayons et Jeux SA'), 
			TO_DATE('15.06.2015','DD.MM.YYYY'),
			'DE-2015.01','Etablissement de devis',
			TO_DATE('08.10.2015','DD.MM.YYYY'),
			TO_DATE('31.12.2015','DD.MM.YYYY'),
			(SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO ='YC'), 100,
			(SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO ='AM'), 3	);

-- 4ème mandat
INSERT INTO MANDATS(	PM_CLIENT_NUMERO, DATESIGNATURE, REFERENCE, DESCRIPTION,
						DATEDEBUT, DATEFINPREVUE,
						COL_CHEFPROJET_NUMERO, NBHEURESCHEFPROJET,
						COL_MANDCOM_NUMERO, NBHEURESMANDCOM		)
VALUES ( 	(SELECT NUMERO FROM PERSONNESMORALES WHERE RAISONSOCIALE ='ABC SA'), 
			TO_DATE('24.09.2015','DD.MM.YYYY'),
			'TI-2015.01','Logiciel de timbrage',
			TO_DATE('10.10.2015','DD.MM.YYYY'),
			TO_DATE('20.12.2015','DD.MM.YYYY'),
			(SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO ='CD'), 45,
			(SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO ='MD'), 10	);

-- 5ème mandat
INSERT INTO MANDATS(	PM_CLIENT_NUMERO, DATESIGNATURE, REFERENCE,DESCRIPTION,
						DATEDEBUT, DATEFINPREVUE,
						COL_CHEFPROJET_NUMERO, NBHEURESCHEFPROJET,
						COL_MANDCOM_NUMERO, NBHEURESMANDCOM		)
VALUES ( 	(SELECT NUMERO FROM PERSONNESMORALES WHERE RAISONSOCIALE ='Cablo SA'), 
			TO_DATE('25.08.2015','DD.MM.YYYY'),
			'FA-2015.03','Logiciel de facturation',
			TO_DATE('28.08.2015','DD.MM.YYYY'),
			TO_DATE('15.11.2015','DD.MM.YYYY'),
			(SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO ='CC'), 80,
			(SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO ='AM'), 5	);

			
-- Script de peuplement de la table des REALISATIONS
INSERT INTO REALISATIONS (MAND_NUMERO, COL_NUMERO, NBHEURES)
VALUES ( (SELECT NUMERO FROM MANDATS WHERE
		 (PM_CLIENT_NUMERO = (SELECT NUMERO FROM PERSONNESMORALES WHERE RAISONSOCIALE ='ABC SA')) AND
		 (DATESIGNATURE = TO_DATE('15.07.2015','DD.MM.YYYY'))),
		 (SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO = 'YC'),
		 36 );

INSERT INTO REALISATIONS (MAND_NUMERO, COL_NUMERO, NBHEURES)
VALUES ( (SELECT NUMERO FROM MANDATS WHERE
		 (PM_CLIENT_NUMERO = (SELECT NUMERO FROM PERSONNESMORALES WHERE RAISONSOCIALE ='ABC SA')) AND
		 (DATESIGNATURE = TO_DATE('15.07.2015','DD.MM.YYYY'))),
		 (SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO = 'SA'),
		 8 );

INSERT INTO REALISATIONS (MAND_NUMERO, COL_NUMERO, NBHEURES)
VALUES ( (SELECT NUMERO FROM MANDATS WHERE
		 (PM_CLIENT_NUMERO = (SELECT NUMERO FROM PERSONNESMORALES WHERE RAISONSOCIALE ='ABC SA')) AND
		 (DATESIGNATURE = TO_DATE('15.07.2015','DD.MM.YYYY'))),
		 (SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO = 'AK'),
		 102 );

INSERT INTO REALISATIONS (MAND_NUMERO, COL_NUMERO, NBHEURES)
VALUES ( (SELECT NUMERO FROM MANDATS WHERE
		 (PM_CLIENT_NUMERO = (SELECT NUMERO FROM PERSONNESMORALES WHERE RAISONSOCIALE ='ABC SA')) AND
		 (DATESIGNATURE = TO_DATE('15.07.2015','DD.MM.YYYY'))),
		 (SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO = 'CS'),
		 4 );

INSERT INTO REALISATIONS (MAND_NUMERO, COL_NUMERO, NBHEURES)
VALUES ( (SELECT NUMERO FROM MANDATS WHERE
		 (PM_CLIENT_NUMERO = (SELECT NUMERO FROM PERSONNESMORALES WHERE RAISONSOCIALE ='ABC SA')) AND
		 (DATESIGNATURE = TO_DATE('15.07.2015','DD.MM.YYYY'))),
		 (SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO = 'VJ'),
		 15 );
		 

-- 2ème mandat
-- 3 REALISATIONS
INSERT INTO REALISATIONS (MAND_NUMERO, COL_NUMERO, NBHEURES)
VALUES ( (SELECT NUMERO FROM MANDATS WHERE
		 (PM_CLIENT_NUMERO = (SELECT NUMERO FROM PERSONNESMORALES WHERE RAISONSOCIALE ='Crayons et Jeux SA')) AND
		 (DATESIGNATURE = TO_DATE('02.05.2015','DD.MM.YYYY'))),
		 (SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO = 'CP'),
		 23 );

INSERT INTO REALISATIONS (MAND_NUMERO, COL_NUMERO, NBHEURES)
VALUES ( (SELECT NUMERO FROM MANDATS WHERE
		 (PM_CLIENT_NUMERO = (SELECT NUMERO FROM PERSONNESMORALES WHERE RAISONSOCIALE ='Crayons et Jeux SA')) AND
		 (DATESIGNATURE = TO_DATE('02.05.2015','DD.MM.YYYY'))),
		 (SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO = 'CF'),
		 122 );

INSERT INTO REALISATIONS (MAND_NUMERO, COL_NUMERO, NBHEURES)
VALUES ( (SELECT NUMERO FROM MANDATS WHERE
		 (PM_CLIENT_NUMERO = (SELECT NUMERO FROM PERSONNESMORALES WHERE RAISONSOCIALE ='Crayons et Jeux SA')) AND
		 (DATESIGNATURE = TO_DATE('02.05.2015','DD.MM.YYYY'))),
		 (SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO = 'CC'),
		 74 );


-- 3ème mandat
-- 4 REALISATIONS
INSERT INTO REALISATIONS (MAND_NUMERO, COL_NUMERO, NBHEURES)
VALUES ( (SELECT NUMERO FROM MANDATS WHERE
		 (PM_CLIENT_NUMERO = (SELECT NUMERO FROM PERSONNESMORALES WHERE RAISONSOCIALE ='Crayons et Jeux SA')) AND
		 (DATESIGNATURE = TO_DATE('15.06.2015','DD.MM.YYYY'))),
		 (SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO = 'CS'),
		 57 );

INSERT INTO REALISATIONS (MAND_NUMERO, COL_NUMERO, NBHEURES)
VALUES ( (SELECT NUMERO FROM MANDATS WHERE
		 (PM_CLIENT_NUMERO = (SELECT NUMERO FROM PERSONNESMORALES WHERE RAISONSOCIALE ='Crayons et Jeux SA')) AND
		 (DATESIGNATURE = TO_DATE('15.06.2015','DD.MM.YYYY'))),
		 (SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO = 'CD'),
		 63 );

INSERT INTO REALISATIONS (MAND_NUMERO, COL_NUMERO, NBHEURES)
VALUES ( (SELECT NUMERO FROM MANDATS WHERE
		 (PM_CLIENT_NUMERO = (SELECT NUMERO FROM PERSONNESMORALES WHERE RAISONSOCIALE ='Crayons et Jeux SA')) AND
		 (DATESIGNATURE = TO_DATE('15.06.2015','DD.MM.YYYY'))),
		 (SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO = 'VJ'),
		 114 );

INSERT INTO REALISATIONS (MAND_NUMERO, COL_NUMERO, NBHEURES)
VALUES ( (SELECT NUMERO FROM MANDATS WHERE
		 (PM_CLIENT_NUMERO = (SELECT NUMERO FROM PERSONNESMORALES WHERE RAISONSOCIALE ='Crayons et Jeux SA')) AND
		 (DATESIGNATURE = TO_DATE('15.06.2015','DD.MM.YYYY'))),
		 (SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO = 'CP'),
		 8 );

-- 4ème mandat
-- Pas de REALISATIONS !

-- 5ème mandat
-- 1 collaboration
INSERT INTO REALISATIONS (MAND_NUMERO, COL_NUMERO, NBHEURES)
VALUES ( (SELECT NUMERO FROM MANDATS WHERE
		 (PM_CLIENT_NUMERO = (SELECT NUMERO FROM PERSONNESMORALES WHERE RAISONSOCIALE ='Cablo SA')) AND
		 (DATESIGNATURE = TO_DATE('25.08.2015','DD.MM.YYYY'))),
		 (SELECT NUMERO FROM COLLABORATEURS WHERE MNEMO = 'CP'),
		 148 );			

COMMIT;	



